# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beam < Formula
  desc "sub-command for scotty to beam logs to scotty"
  homepage "https://github.com/KonstantinGasser/beam"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/KonstantinGasser/beam/releases/download/v0.0.1/beam_Darwin_all.tar.gz"
    sha256 "6131086bbf4bf5cf739aa91bc25484d9907daaa53fcc36c3245af7511bc9ed1e"

    def install
      bin.install "beam"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KonstantinGasser/beam/releases/download/v0.0.1/beam_Linux_arm64.tar.gz"
      sha256 "55ab35f653cac4fd155cedf0cddbf56f4d8fbc01495a9405b0b8df3c4778ba68"

      def install
        bin.install "beam"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KonstantinGasser/beam/releases/download/v0.0.1/beam_Linux_x86_64.tar.gz"
      sha256 "2be7bb214c1b443ca4dbb1190b2028f5194d5502fed823bbadd757eb6e4870b9"

      def install
        bin.install "beam"
      end
    end
  end
end
