# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scotty < Formula
  desc "Multiplex log streams in your local environment"
  homepage "https://github.com/KonstantinGasser/scotty"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/KonstantinGasser/scotty/releases/download/v0.0.1/scotty_Darwin_all.tar.gz"
    sha256 "c36e8e05df8a3a7f192934eff5d9f26718c615393462dce2af46f0ffac8d2f94"

    def install
      bin.install "scotty"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KonstantinGasser/scotty/releases/download/v0.0.1/scotty_Linux_arm64.tar.gz"
      sha256 "a20628aadb9b98e50841b52b1e921312a492b9a41105e37457443c676de4e8d4"

      def install
        bin.install "scotty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KonstantinGasser/scotty/releases/download/v0.0.1/scotty_Linux_x86_64.tar.gz"
      sha256 "f5ddf0f2794579faf3f9054ce187e6045bae64c0316f3d744a381c2740d10062"

      def install
        bin.install "scotty"
      end
    end
  end
end
