# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scotty < Formula
  desc "sub-command for scotty to beam logs to scotty"
  homepage "https://github.com/KonstantinGasser/scotty"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/KonstantinGasser/beam/releases/download/v0.0.1/beam_Darwin_all.tar.gz"
    sha256 "4dcbdfadcffe2ed229bcf118bbac905f165e107f649ea1338d09d43270e38614"

    def install
      bin.install "beam"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KonstantinGasser/beam/releases/download/v0.0.1/beam_Linux_arm64.tar.gz"
      sha256 "da0d5d57f38614ffae9f7ce2169a104d280d57a2c913e40c68c52373d9e97b4f"

      def install
        bin.install "beam"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KonstantinGasser/beam/releases/download/v0.0.1/beam_Linux_x86_64.tar.gz"
      sha256 "4f4ee2f51fd419690caefb8f0537fc677a8aa9b8b80a6faa670d01470f5c0bae"

      def install
        bin.install "beam"
      end
    end
  end
end
